[[custom_groups]]
name = "ğŸ”° é»˜è®¤èŠ‚ç‚¹"
type = "select"
rule = [
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ¯ é»˜è®¤ç›´è¿",
    ".*"
]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 1800

[[custom_groups]]
name = "ğŸŒ å›½é™…æµåª’ä½“"
type = "select"
rule = [
    "[]ğŸ”° é»˜è®¤èŠ‚ç‚¹",
    "[]ğŸ¯ é»˜è®¤ç›´è¿",
    ".*"
]

[[custom_groups]]
name = "ğŸï¸ NETFLIX"
type = "select"
rule = [
    "[]ğŸŒ å›½é™…æµåª’ä½“",
    ".*"
]

[[custom_groups]]
name = "ğŸï¸ HBO"
type = "select"
rule = [
    "[]ğŸŒ å›½é™…æµåª’ä½“",
    ".*"
]

[[custom_groups]]
name = "ğŸï¸ Disney+"
type = "select"
rule = [
    "[]ğŸŒ å›½é™…æµåª’ä½“",
    ".*"
]

[[custom_groups]]
name = "ğŸ“º ä¸­å›½æµåª’ä½“"
type = "select"
rule = [
    "[]ğŸ¯ é»˜è®¤ç›´è¿",
    "[]ğŸ”° é»˜è®¤èŠ‚ç‚¹",
    "[]ğŸŒ å›½é™…æµåª’ä½“",
    "(HGC|HKBN|PCCW|HKT|æ·±å°|å½°åŒ–|æ–°åŒ—|å°|hk|æ¸¯|tw)"
]

[[custom_groups]]
name = "â“‚ï¸ Microsoft"
type = "select"
rule = [
    "[]ğŸ”° é»˜è®¤èŠ‚ç‚¹",
    "[]ğŸ¯ é»˜è®¤ç›´è¿",
    ".*"
]

[[custom_groups]]
name = "ğŸ Apple"
type = "select"
rule = [
    "[]ğŸ”° é»˜è®¤èŠ‚ç‚¹",
    "[]ğŸ¯ é»˜è®¤ç›´è¿",
    ".*"
]

[[custom_groups]]
name = "ğŸ’° PayPal"
type = "select"
rule = [
    "[]ğŸ”° é»˜è®¤èŠ‚ç‚¹",
    "[]ğŸ¯ é»˜è®¤ç›´è¿",
    ".*"
]

[[custom_groups]]
name = "ğŸ“ å­¦æœ¯"
type = "select"
rule = [
    "[]ğŸ”° é»˜è®¤èŠ‚ç‚¹",
    "[]ğŸ¯ é»˜è®¤ç›´è¿",
    ".*"
]

[[custom_groups]]
name = "ğŸ“² Telegram"
type = "select"
rule = [
    "[]ğŸ”° é»˜è®¤èŠ‚ç‚¹",
    ".*"
]

[[custom_groups]]
name = "ğŸ¯ é»˜è®¤ç›´è¿"
type = "select"
rule = [
    "[]DIRECT",
    "[]ğŸ”° é»˜è®¤èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸ›‘ é»˜è®¤æ‹¦æˆª"
type = "select"
rule = [
    "[]REJECT", 
    "[]DIRECT",
    "[]ğŸ”° é»˜è®¤èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸ•³ï¸ è§„åˆ™ä¹‹å¤–"
type = "select"
rule = [
    "[]ğŸ”° é»˜è®¤èŠ‚ç‚¹",
    "[]ğŸ¯ é»˜è®¤ç›´è¿"
]
