[[rulesets]]
group = "ğŸ¯ é»˜è®¤ç›´è¿"
ruleset = "rules/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ Apple"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Apple/Apple.list"

[[rulesets]]
group = "â“‚ï¸ Microsoft"
ruleset = "rules/MSServices.list"

[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Telegram/Telegram.list"

[[rulesets]]
group = "ğŸ’° PayPal"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/PayPal.list"

[[rulesets]]
group = "ğŸ“ å­¦æœ¯"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Scholar.list"

[[rulesets]]
group = "ğŸ¯ é»˜è®¤ç›´è¿"
ruleset = "rules/DivineEngine/Surge/Ruleset/Unbreak.list"

[[rulesets]]
group = "ğŸ›‘ é»˜è®¤æ‹¦æˆª"
ruleset = "rules/DivineEngine/Surge/Ruleset/Guard/Hijacking.list"

[[rulesets]]
group = "ğŸï¸ NETFLIX"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/Netflix.list"

[[rulesets]]
group = "ğŸŒ å›½é™…æµåª’ä½“"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Streaming.list"

[[rulesets]]
group = "ğŸ“º ä¸­å›½æµåª’ä½“"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/StreamingSE.list"

[[rulesets]]
group = "ğŸ“º ä¸­å›½æµåª’ä½“"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/WeTV.list"

[[rulesets]]
group = "ğŸ“º ä¸­å›½æµåª’ä½“"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/iQIYI.list"

[[rulesets]]
group = "ğŸ“º ä¸­å›½æµåª’ä½“"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/bilibili-Intl.list"

[[rulesets]]
group = "ğŸ”° é»˜è®¤èŠ‚ç‚¹"
ruleset = "rules/DivineEngine/Surge/Ruleset/Global.list"

[[rulesets]]
group = "ğŸ¯ é»˜è®¤ç›´è¿"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/StreamingCN.list"

[[rulesets]]
group = "ğŸ¯ é»˜è®¤ç›´è¿"
ruleset = "rules/DivineEngine/Surge/Ruleset/China.list"

[[rulesets]]
group = "ğŸ¯ é»˜è®¤ç›´è¿"
ruleset = "rules/NobyDa/Surge/Download.list"

[[rulesets]]
group = "ğŸ¯ é»˜è®¤ç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ•³ï¸ è§„åˆ™ä¹‹å¤–"
ruleset = "[]FINAL"
